### ISSUE TITLE
ETA on .NET Standard 2.0 non beta package?

### ISSUE THREAD

**Issue by danielwertheim** [JanKallman/EPPlus#101]
Latest beta release was two months ago (including .NET Standard support #46 ). Is there any ETA on when the stable release will support .NET Standard 2.0?

**Comment by JanKallman** [comment]
The problem is that the EPPlus 4.5-.Net Standard 2.0 version uses an early preview of System.Drawing.Common (and before that, unofficial beta versions). Otherwise we are pretty much ready for a stable release. As a stable version of System.Drawing.Common seems to take some time and it's not that heavily used in EPPlus we should consider realeasing it anyway. 
I'll get back in the matter.

**Comment by JanKallman** [comment]
4.5.1 is now out, but with System.Drawing.Common preview 3.
