### ISSUE TITLE
Wrong column width

### ISSUE THREAD

**Issue by Pekshev** [JanKallman/EPPlus#89]
In the help for excel  is written that the standard width of the column is 8,43 characters.
EPPlus return 9,140625 characters.
Created an Excel document and set the width of the column to 255 characters (maximum) - EPPlus returned 255,7109375 characters

**Comment by Pekshev** [comment]
I tested your library and the standard COM library. With the standard font (Calibri, 11) your library returns a value of 0.710625 more each time:
Interop: Standard width: 8,43
Interop: Column.ColumnWidth: 58
EPPlus: MaxFontWidth: 7
EPPlus: ws.DefaultColWidth: 9,140625
EPPlus: Column 1 width: 58,7109375
and
Interop: Standard width: 8,43
Interop: Column.ColumnWidth: 53,14
EPPlus: MaxFontWidth: 7
EPPlus: ws.DefaultColWidth: 9,140625
EPPlus: Column 1 width: 53,85546875
etc.

**Comment by JanKallman** [comment]
EPPlus returns the width from the column tag in the package, located in the worksheet xml file. This differs from value in Excel. Check the ooxml documentation  for more details. This is by design.

**Comment by massonib** [comment]
I was having this struggle while placing an image using ExcelPicture.SetPosition(). The best solution I've found I have posted below since it may be of help to someone. Basically OOXML and Excel don't agree with the Width/Height dimension, but they always agree with the number of pixels that make up a column and row. So, if you want the pixel value for a specific row/column, you can just iterate over the rows/columns summing their pixelHeight/pixelWidth as you go. This is more accurate than summing the height/width and then converting it to pixels. Note: auto sizing and style changes may change the result, so do them beforehand. 

using mdw = xlWorksheet.Workbook.MaxFontWidth;  
pixelHeight = (int)(worksheet.Row(rowIndex).Height / 0.75);
pixelWidth = (int) decimal.Truncate(((256 * (decimal) worksheet.Column(columnIndex).Width +
                                              decimal.Truncate(128 / (decimal) mdw)) / 256) * mdw);

**Comment by PriyankGadhiya** [comment]
I use this EPPlus  library and use code like this in it, but code does not work

for (int i = 1; i < ws.Cells.Count() + 3; i++)
                    {
                        ws.Column(i).AutoFit();
                    }

**Comment by massonib** [comment]
I have never used Cell.Count(), so I'm not sure what that integer value is, but it may be your problem. Also, I expect it may be faster to AutoFit all the columns at once with something like this:

var range = worksheet.Cells[startRow, startColumn, endRow, endColumn]; 
range.AutoFitColumns();

You likely could just use 1 for the start and end row, but I have not checked that out.
